modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="create_new_age_accumulators"
version="1.6.1"
displayName="Create: New Age: Accumulators"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-new-age-accumulators"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Robo-dude999999, MCreator"
description="Adds an energy storage system to Create: New Age."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_new_age_accumulators]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration